language: node_js
node_js:
  - '12'
before_deploy:
  - npm run build
  - cd dist
deploy:
  provider: npm
  api_key: '$NPM_API_TOKEN'
  email: '$NPM_EMAIL'
  edge: true
  skip_cleanup: true
  on:
    tags: true
