version: 2.1
jobs:
  build:
    docker:
      - image: hesto2/aws-terraform-node12:latest
    steps:
      - checkout
      - run:
          name: Publish package
          command: sh ./bin/npm-publish.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: hesto2-npm
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master