version: 2.1
jobs:
  build:
    docker:
      - image: hesto2/aws-terraform-node12:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            yarn install
      - run:
          name: Build
          command: |
            CI="" yarn build
      - run:
          name: Authenticate with registry
          command: echo "//packagecloud.io/armando/node-test-package/npm/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: hesto2-npm
          filters:
            branches:
              only:
                - master